name: preprocess-dataset

on:
  push:
    paths:
      - "telco_raw/**"
      - "preprocessing/**"
      - ".workflow/requirements.txt"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .workflow/requirements.txt

      - name: Run preprocessing automation
        run: |
          python preprocessing/automate_VidiJoshubzkySaviola.py \
            --input telco_raw/Telco-Customer-Churn.csv \
            --output preprocessing/telco_preprocessing

      - name: Upload preprocessed dataset as artifact
        uses: actions/upload-artifact@v4
        with:
          name: telco_preprocessed
          path: preprocessing/telco_preprocessing
